# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

permTQuantile <- function(X, B, label) {
    .Call('_qpARI_permTQuantile', PACKAGE = 'qpARI', X, B, label)
}

pvQuantile <- function(QT, Test, B) {
    .Call('_qpARI_pvQuantile', PACKAGE = 'qpARI', QT, Test, B)
}

rcpparma_hello_world <- function() {
    .Call('_qpARI_rcpparma_hello_world', PACKAGE = 'qpARI')
}

rcpparma_outerproduct <- function(x) {
    .Call('_qpARI_rcpparma_outerproduct', PACKAGE = 'qpARI', x)
}

rcpparma_innerproduct <- function(x) {
    .Call('_qpARI_rcpparma_innerproduct', PACKAGE = 'qpARI', x)
}

rcpparma_bothproducts <- function(x) {
    .Call('_qpARI_rcpparma_bothproducts', PACKAGE = 'qpARI', x)
}

rowSortC <- function(X) {
    .Call('_qpARI_rowSortC', PACKAGE = 'qpARI', X)
}

signFlipQuantile <- function(X, B) {
    .Call('_qpARI_signFlipQuantile', PACKAGE = 'qpARI', X, B)
}

